# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "To a new beta build"
  lane :beta do
    build_type "Release"
    increment_build_number(xcodeproj: "rnshell.xcodeproj")
    build_app(
      configuration: build_type,
      clean: true,
      include_symbols: true,
      include_bitcode: false,
      output_directory: "../build/ios", # Destination directory. Defaults to current directory.
      output_name: "rnshell_"+build_type+"_app.ipa",
      export_method: "development", # app-store, package, ad-hoc, enterprise, development
      workspace: "rnshell.xcworkspace",
      scheme: "rnshell")
  end

  desc "Push a new beta build to TestFlight"
  lane :testflight do
    increment_build_number(xcodeproj: "rnshell.xcodeproj")
    build_app(workspace: "rnshell.xcworkspace", scheme: "rnshell")
    upload_to_testflight
  end

end
