# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# 配置信息
# {
#   "key_id": "223576V89G",
#   "issuer_id": "6bcbdcb8-7dba-46e2-810a-f3475add5cf6",
#   "key": "",
#   "duration": 1200,
#   "in_house": false
# }
api_key_path = "./fastlane/key.json";

# use ENV['MATCH_GIT_BASIC_AUTHORIZATION'] = '<YOUR BASE64 KEY>'
# use ENV['MATCH_PASSWORD'] = '<YOUR MATCH_PASSWORD>'
# match(git_basic_authorization: '')

# 获取当前的时间
today = Time.new;
now_time = today.strftime("%Y%m%d%H%M%S");
# 通过时间戳截取获取版本code
ttime = Time.now.to_i.to_s
build_number = ttime[2,7]
# 版本号
version_name = "1.1.0"

# 当前APP信息
app_name = get_info_plist_value(path: "./rnshell/Info.plist", key: "CFBundleDisplayName")
identifier = get_info_plist_value(path: "./rnshell/Info.plist", key: "CFBundleIdentifier")
puts "APP_NAME: #{app_name}"
puts "applicationId: #{identifier}"
puts "versionCode: #{build_number}"
puts "versionName: #{version_name}"
puts "timestamp: #{ttime}"
puts "nowtime: #{now_time}"

# 原构建号信息
o_build_number =  get_build_number(xcodeproj: "rnshell.xcodeproj")


platform :ios do
  desc "To a new beta Release build"
  lane :release do
    build_type = "Release"
    setup_ci
    # register_devices(
    #   devices: {
    #     # "iPhone 6" => "1234567890123456789012345678901234567890",
    #   }
    # )
    match(type: "adhoc", readonly: is_ci, force_for_new_devices: true)
    # exec("security unlock-keychain -p #{MATCH_PASSWORD} login.keychain")
    increment_build_number(build_number: "#{build_number}", xcodeproj: "rnshell.xcodeproj")
    # get_provisioning_profile(force: true, api_key_path: api_key_path)
    # sync_code_signing(type: "development", api_key_path: api_key_path)
    sync_code_signing()
    # 设置plist信息
    update_info_plist(
      plist_path: "./rnshell/Info.plist",
    )
    update_code_signing_settings
    build_app(
      configuration: build_type,
      clean: true,
      skip_codesigning: true,
      # skip_package_ipa: true,
      include_symbols: true,
      include_bitcode: false,
      output_directory: "./build/#{build_type.downcase}/#{version_name}/", # Destination directory. Defaults to current directory.
      output_name: "rnshell_#{build_type.downcase}_#{version_name}_#{now_time}.ipa",
      workspace: "rnshell.xcworkspace",
      # export_xcargs: "-allowProvisioningUpdates", # auto sign
      scheme: "rnshell",
      export_method: "ad-hoc", # app-store, package, ad-hoc, enterprise, development
      export_options: {
				method: "ad-hoc",
				compileBitcode: false,
        # provisioningProfiles: {
        #   "#{identifier}" => "match AdHoc #{identifier}"
        # }
			})
    # 还原构建号
    increment_build_number(build_number: "#{o_build_number}", xcodeproj: "rnshell.xcodeproj")
    # 蒲公英上传
    pgyer(api_key: "469f2987b4bb1eb2d826df2c31624ffc", user_key: "3e98a606c3614770b06b044af8ec8c1d")
    # # fir上传
    # file_path =  lane_context[SharedValues::IPA_OUTPUT_PATH]
    # answer = fir_cli api_token: "644fa3d8f235883fc8a62a6e66a2edbf", specify_file_path: "#{file_path}", need_release_id: true, changelog: ""
    # # 获取更新下载二维码图片链接
    # puts "fir上传后的结果： #{answer} "
  end

  desc "To a new dev Debug build"
  lane :debug do
    build_type = "Debug"
    setup_ci
    obuild_number =
    increment_build_number(build_number: "#{build_number}", xcodeproj: "rnshell.xcodeproj")
    # get_provisioning_profile(force: true, api_key_path: api_key_path)
    # sync_code_signing(type: "development", api_key_path: api_key_path)
    sync_code_signing()
    # 设置plist信息
    update_info_plist(
      plist_path: "./rnshell/Info.plist",
      display_name: "#{app_name}dev",
      app_identifier: "#{identifier}dev"
    )
    update_code_signing_settings

    build_app(
      configuration: build_type,
      clean: true,
      # skip_build_archive: false,
      # skip_archive: false,
      include_symbols: true,
      include_bitcode: false,
      output_directory: "./build/#{build_type.downcase}/#{version_name}/", # Destination directory. Defaults to current directory.
      output_name: "rnshell_#{build_type.downcase}_#{version_name}_#{now_time}.ipa",
      workspace: "rnshell.xcworkspace",
      scheme: "rnshell",
      xcargs: "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) DEBUG=1'",
      export_method: "development", # app-store, package, ad-hoc, enterprise, development
      export_options: {
				method: "development",
				compileBitcode: false
			})
    # 设置开发信息
    update_info_plist(
      plist_path: "./rnshell/Info.plist",
      display_name: "#{app_name}",
      app_identifier: "#{identifier}"
    )
    # 还原构建号
    increment_build_number(build_number: "#{o_build_number}", xcodeproj: "rnshell.xcodeproj")
    # 蒲公英上传
    pgyer(api_key: "469f2987b4bb1eb2d826df2c31624ffc", user_key: "3e98a606c3614770b06b044af8ec8c1d")
    # # fir上传
    # file_path =  lane_context[SharedValues::IPA_OUTPUT_PATH]
    # answer = fir_cli api_token: "644fa3d8f235883fc8a62a6e66a2edbf", specify_file_path: "#{file_path}", need_release_id: true, changelog: ""
    # # 获取更新下载二维码图片链接
    # puts "fir上传后的结果： #{answer} "
  end

  desc "Push a new beta build to TestFlight"
  lane :testflight do
    increment_build_number(xcodeproj: "rnshell.xcodeproj")
    build_app(workspace: "rnshell.xcworkspace", scheme: "rnshell")
    upload_to_testflight
  end

end
