# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Beta"
  lane :beta do
    gradle(task: "app:assembleRelease --profile")
    # crashlytics
    # sh "your_script.sh"
    # You can also use other beta testing services here
    firim(firim_api_token:"644fa3d8f235883fc8a62a6e66a2edbf")
    pgyer(api_key: "469f2987b4bb1eb2d826df2c31624ffc", user_key: "3e98a606c3614770b06b044af8ec8c1d")
  end

  lane :debug do
    gradle(task: "app:assembleDebug --profile")
    # 多个参数 可以使用逗号(, )分离
    firim(firim_api_token:"644fa3d8f235883fc8a62a6e66a2edbf")
    pgyer(api_key: "469f2987b4bb1eb2d826df2c31624ffc", user_key: "3e98a606c3614770b06b044af8ec8c1d")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean app:assembleRelease")
    upload_to_play_store
  end
end
