name: Android Build- Github Actions

on:
  push:
    branches:
        - master

jobs:
  build-release:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
    - uses: actions/checkout@v2
    - name: Envinfo
      run: npx envinfo
    - name: Build application
      run: yarn install && cd android && chmod +x gradlew && cd ../ && yarn pack-android
  build-debug:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
    - uses: actions/checkout@v2
    - name: Envinfo
      run: npx envinfo
    - name: Build application
      run: yarn install && cd android && chmod +x gradlew && cd ../ && yarn pack-android --mode debug
