name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Envinfo
      run: npx envinfo
    - name: Build application
      run: yarn install && yarn pack-ios --api_secret ${{ secrets.IOS_API_SECRET_FASTLANE }}
  build-debug:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Envinfo
      run: npx envinfo
    - name: Build application
      run: yarn install && yarn pack-ios --mode debug --api_secret ${{ secrets.IOS_API_SECRET_FASTLANE }}
