name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Envinfo
      run: npx envinfo
    - name: Build application
      env:
        API_SECRET: ${{ secrets.IOS_API_SECRET_FASTLANE }}
      run: yarn install && yarn pack-ios --api_secret "$API_SECRET"
  build-debug:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Envinfo
      run: npx envinfo
    - name: Build application
      env:
        API_SECRET: ${{ secrets.IOS_API_SECRET_FASTLANE }}
      run: yarn install && yarn pack-ios --api_secret "$API_SECRET" --mode debug
